Modules/Inventory/Http/routes.php
<?php

Route::group(['middleware' => ['web','auth'], 'prefix' => 'inventory', 'namespace' => 'Modules\Inventory\Http\Controllers'], function()
{
    // show page or next page
    Route::get('/', 'InventoryController@index')->name("inventory.index");
    Route::resource('EveryFiles','EveryFilesController');
    Route::resource('SpecificFile','ModalFilesController');
    Route::resource('Conversations','ConvFilesController');

    // ========== haha boom! ============
    Route::get('/inventory/INBOX','EveryFilesController@receivedFiles')->name('display.RECEIVED');
    Route::get('/inventory/OUTBOX','EveryFilesController@sentFiles')->name('display.SENT');
    Route::get('/inventory/MESSAGES','EveryFilesController@allFiles')->name('display.ALL');
    Route::get('/inventory/IMPORTANT','EveryFilesController@importantFiles')->name('display.IMPS');

    // ========== haha boom! ============
    Route::get('/admin/INBOX','EveryFilesController@receivedFiles')->name('displayAdmin.RECEIVED');
    Route::get('/admin/OUTBOX','EveryFilesController@sentFiles')->name('displayAdmin.SENT');
    Route::get('/admin/MESSAGES','EveryFilesController@allFiles')->name('displayAdmin.ALL');
    Route::get('/admin/IMPORTANT','EveryFilesController@importantFiles')->name('displayAdmin.IMPS');
});

Modules/Inventory/Resources/views/files/_allUsers.blade.php
<!-- ___________________MODAL TO VIEW ALL USERS FOR SETTING RECEIVER __________________ -->
  <div class="modal fade" id="modal-allUsers-file" type="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Select Recepients</h4>
        </div>
        <div class="modal-body">
        	
        	<input type="text" id="searchNamesHere" class="form-control form-control-pad" onkeyup="dispTableFunction()" placeholder="Search Names..">
        	<input type="text" id="searchNamesHeres" class="form-control form-control-pad" onkeyup="dispTableFunctions()" placeholder="Search Departments..">

			<table class="table table-striped table-bordered table-hover" id="dispTable">
				<thead>
			  		<tr>
				    	<td>Name</td>
				    	<td>Department</td>
				 	</tr>
				</thead>
				<tbody>
					@foreach($emps as $emps)
						<tr onclick="selectedFunction();">
							<td>
								<input name="Recepients" type="checkbox" value="{{$emps->emp_id}}" id="checkboxes"> &nbsp; &nbsp; &nbsp;
								{{$emps->f_name}} {{$emps->l_name}}
							</td>
							<td>
								{{$emps->dept_name}}
							</td>
			  			</tr>
			  		@endforeach
			  	</tbody>
			</table>
        </div>
        <div class="modal-footer">
        	<a class="btn btn-new btn-lg previousStep" href="#modal-create-file" data-toggle="modal" data-dismiss="modal">Select</a>
        	<a class="btn btn-new btn-lg previousStep" href="#modal-create-file" data-toggle="modal" data-dismiss="modal">Cancel</a>
        </div>
        
      </div>
      
    </div>
  </div>

Modules/Inventory/Resources/views/files/_createFile.blade.php
<!-- ___________________MODAL TO CREATE NEW FILE__________________ -->
  <div class="modal fade" id="modal-create-file" type="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
            <div class="msgTabs">
              <button>New Message</button>
              <!-- <button class="msgTabslinks" onclick="openMsg(event, 'UMsg')">Urgent Message</button> -->
              <button type="button" data-dismiss="modal" class="pull-right">Cancel</button>
            </div>
<!-- ==================================== CREATE NORMAL FILE ==================================== -->
            <!-- <div id="NMsg" class="msgTabscontent"> -->
            <div>
                @include('inventory::includes._createNFile')
            </div>
<!-- ==================================== CREATE URGENT FILE ==================================== -->
            <div id="UMsg" class="msgTabscontent">
                @include('inventory::includes._createUFile')
            </div>
        </div>
      </div>
    </div>
  </div>

Modules/Inventory/Resources/views/files/_editFile.blade.php
<!-- ___________________MODAL TO CREATE NEW FILE__________________ -->
                      <div class="modal fade" id="modal-edit-file" role="dialog">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal">&times;</button>
                              <h4 class="modal-title">New File</h4>
                            </div>
                            <div class="modal-body">
                                <form class="thing-form" role="form" name="newFile" id="newFile" method="post" >
                                    {{ csrf_field() }}


                                    <div class="form-group has-feedback">
                                        <div class="form-group">
                                            <label class="control-label float-left" for="fileName">File Name</label>
                                            <div class="form-group form-group-pad">
                                                <input type="text" class="form-control form-control-pad" name="fileName" placeholder="File Name">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label float-left" for="receiver">Receiver</label>
                                            <div class="form-group form-group-pad seee">
                                                <input type="text" class="form-control form-control-pad " name="receiver" placeholder="Employee Name or ID">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label float-left" for="fileText">Content</label>
                                            <div class="form-group form-group-pad">
                                                <textarea type="text" class="form-control form-control-pad textContent" name="fileText" placeholder="Your Message"></textarea>
                                            </div>

                                        </div>
                                    </div>
                                    <br>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-lg " data-dismiss="modal">Cancel</button>
                                        <button type="button" class="btn btn-new btn-lg" data-dismiss="modal">Save</button>
                                        <button type="button" class="btn btn-new btn-lg" data-dismiss="modal">Send File</button>
                                    </div>
                                </form>
                            </div>
                            
                          </div>
                          
                        </div>
                      </div>

Modules/Inventory/Resources/views/files/_impFiles.blade.php
 @extends('template::admin-pages.menus.'.$template['menu']) 

@section('plugins-css')
    <link rel="stylesheet" href="{{asset('adminlte')}}/plugins/datatables/dataTables.bootstrap.css">
@stop

@section('pagename')
    
    <span style="font-size: 25px;">
        @include('inventory::includes._titleFILE')
    </span>
@stop

@section('content')
    <div class="content-wrapper">
        <section class="content">
            @if (($tite_page)=='Home')
                @include('inventory::includes._homeShortcuts')
            @endif
            <div class="box">
                <div class="box-header">
                    
                </div>
                <div class="box-body">
                    <div class="col-lg-8">
                    <table class="table table-striped table-bordered" id="tablet">
                        <thead>
                            <tr>
                                <td></td>
                                <td>Tracking No.</td>
                                <td>File Name</td>
                                @if(($tite_page)=='Received Files')
                                    <td>Sender</td>
                                @elseif(($tite_page)=='Sent Files')
                                    <td>Receiver</td>
                                @else
                                    <td>Sender</td>
                                    <td>Receiver</td>
                                @endif
                                <td>Attachement</td>
                                <td></td>
                            </tr>
                            
                        </thead>
                        <tbody>
                            @foreach($per_files as $per_files)
                                <a href="{{ URL::route('SpecificFile.show',$per_files->tracking_no) }}">
                                <tr>
                                    <td>@include('inventory::includes._markImpFile')</td>
                                    <td>{{$per_files->tracking_no}}</td>
                                    <td>{{$per_files->file_name}}</td>
                                    
                                    @if(($tite_page)=='Received Files')
                                        <td>
                                            @if(($per_files->senderID) == (Auth::user()->emp_id))
                                                ME (=^_^=)!!!
                                            @else
                                                {{$per_files->dept_name}} <br>
                                                ---- {{$per_files->f_name}} {{$per_files->l_name}} ----
                                            @endif
                                        </td>
                                    @elseif(($tite_page)=='Sent Files')
                                        <td>
                                             @if(($per_files->receiverID) == (Auth::user()->emp_id))
                                                ME (=^_^=)!!!
                                            @else
                                                {{$per_files->dept_name}} <br>   
                                                ---- {{$per_files->f_name}} {{$per_files->l_name}} ----
                                            @endif
                                        </td>
                                        
                                    @else
                                        <td>
                                            @if(($per_files->senderID) == (Auth::user()->emp_id))
                                                ME (=^_^=)!!!
                                            @else
                                                {{$per_files->deptID_of_sender}} <br> 
                                                <a href="" data-toggle="modal" data-target="#modal-view-personnel"> 
                                                    ---- {{$per_files->_extra2}} ---- 
                                                </a>
                                            @endif
                                        </td>
                                        <td>
                                            @if(($per_files->receiverID) == (Auth::user()->emp_id))
                                                ME (=^_^=)!!!
                                            @else
                                                {{$per_files->deptID_of_receiver}} <br> 
                                                <a href="" data-toggle="modal" data-target="#modal-view-personnel">
                                                    ---- {{$per_files->_extra1}} ----
                                                </a>
                                            @endif
                                        </td>
                                    @endif
                                    <td>
                                        <a href="">{{$per_files->attachment_name}}</a>
                                    </td>
                                    <td>
                                        <a href="{{URL::route('SpecificFile.show',$per_files->tracking_no)}}">View</a>
                                        
                                    </td>
                                </tr>
                                </a>
                            @endforeach
                        </tbody>
                    </table>
                    @if(Session::has('message'))
                        <div class="alert alert-success pull-right alertSession" onload="alerts()">{{Session::get('message')}}</div>
                    @endif

                        
                    <!-- ___________ ALL INCLUDES _____________ -->
                    @include('inventory::includes._ALL')  
                    </div>
                    <div class="col-lg">
                        <button type="button" class="btn btn-new pull-right" data-toggle="modal" data-target="#modal-create-file"><i class="glyphicon glyphicon-pencil"></i> &nbsp; Compose</button> 
                        
                    </div>
                </div>
                


            </div>
        </section>
    </div>
@stop

@section('plugins-script')
    <script src="{{asset('adminlte')}}/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="{{asset('adminlte')}}/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="{{asset('adminlte')}}/plugins/daterangepicker/moment.js"></script>
    <script src="{{asset('js')}}/jquery.min.js"></script>
    <script src="{{asset('js')}}/moment.min.js"></script>
    <script src="{{asset('js')}}/fullcalendar.min.js"></script>

@stop

Modules/Inventory/Resources/views/files/_specific_file.blade.php
 @extends('template::admin-pages.menus.'.$template['menu']) 

@section('plugins-css')
    <link rel="stylesheet" href="{{asset('adminlte')}}/plugins/datatables/dataTables.bootstrap.css">
@stop

@section('pagename')
    <span style="font-size: 25px;">{{$tite_page}}</span>
@stop

@section('content')
    <div class="content-wrapper">
      <section class="content">
        <div class="box">
          <div class="box-header">

              <a class="btn btn-default btn-lg nextStep" href="{{URL::route('EveryFiles.show','SENT_FILES')}}" data-toggle="modal" data-dismiss="modal"><span class="glyphicon glyphicon-arrow-left"></span>&nbsp; Back</a>
              
              <span style="border-bottom:1px solid black;">@include('inventory::includes._markImpFile')</span>
              <script type="text/javascript">
                var timestamp = 0;

                setInterval(function(){
                    $.ajax({
                        url:"confess_show.php?t=" + timestamp,
                        type:"GET",
                        dataType:"html",
                        success:function(data){
                            if(data != ''){ //Only append data if there are some new
                                timestamp = Math.round((new Date()).getTime() / 1000); //Set timestamp to current time
                                $('.content').append(data);
                            }
                        }
                    });
                }, 6000);
              </script>
          </div>
          <div class="box-body">
            <div class="col-md-9" style="margin-left: auto; margin-right: auto; border-right: 1px solid #ccc;">
              <h3>{{$per_files->file_name}}</h3>
                  
              @if(($per_files->senderID)==(Auth::user()->emp_id))
                
                <h4>To: <b> {{$per_files->f_name}} {{$per_files->l_name}}</b> of {{$per_files->dept_name}}</h4>
                <h5>DATE SENT: {{$per_files->created_at}}</h5>
              
              @else
              
                <h4>From: <b> {{$per_files->f_name}} {{$per_files->l_name}}</b> of {{$per_files->dept_name}}</h4>
                <h5>DATE Received:     {{$per_files->created_at}}</h5>
              
              @endif

              <hr style="width:50%;">
              {{$per_files->remarks}}
              <br>
              <a href="">{{$per_files->attachment_name}}</a>
              
              <br><hr>
            </div>
            <!-- ============ BUTTON STUFF ===================== -->
            <div class="col-md-3 moreMenu" style="padding:0px;">
              <ul style="list-style-type: none; padding: 0px;">
                <li style="padding-bottom: 10px;">
                  <a class="btn btn-new btn-block nextStep" href="#reply_modal" data-toggle="modal" data-dismiss="modal"><span class="glyphicon glyphicon-arrow-right"></span> &nbsp;Reply</a>
                </li>
                <li style="padding-bottom: 10px;">  
                  <a class="btn btn-new btn-block nextStep" href="#edit_file" data-toggle="modal" data-dismiss="modal"><span class="glyphicon glyphicon-share-alt"></span> &nbsp; Forward</a>
                </li>
                <li>
                  <a class="btn btn-new btn-block nextStep" href="#alert_modal" data-toggle="modal" data-dismiss="modal"><span class="glyphicon glyphicon-trash"></span> &nbsp; Delete</a>
                </li>
              </ul> 
            </div>

            <!-- ============================ MODAL FOR ALERT MESSAGE FOR DELETING MESSAGES =================== -->
            <div class="modal fade" id="alert_modal" type="dialog">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header" style="text-align: center;">
                    <h4>ARE YOU SURE?</h4>
                  </div>
                  <div class="modal-body" style="align-content: center; text-align: center;">
                    <form method="Delete" action="{{URL::route('Conversations.destroy',$per_files->tracking_no)}}">
                    {{ csrf_field() }}
                      <button type="submit" class="btn btn-primary btn-lg">Delete</button>
                      <button class="btn btn-new btn-lg" data-toggle="modal" data-dismiss="modal">Cancel</button>
                    </form>
                    </div>
                </div>
              </div>
            </div>


            <!-- =================================== MODAL FOR REPLYING A MESSAGE =============================== -->
            <div class="modal fade" id="reply_modal" type="dialog">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4>To: {{$per_files->f_name}} {{$per_files->l_name}}</h4>
                  </div>
                  <div class="modal-body">
                    <form method="Delete" action="{{URL::route('Conversations.index',$per_files->tracking_no)}}">
                    {{ csrf_field() }}
                      <!-- ____CONTENT____ -->
                      <div class="form-group">
                          <label class="control-label float-left" for="fileText">Message</label>
                          <div class="form-group form-group-pad">
                              <textarea type="text" class="form-control form-control-pad textContent" name="fileText" placeholder="Your Message"></textarea>
                          </div>
                      </div>
              <!-- _____URGENT FILE_____ -->
                      <div class="form-group">
                          <label class="control-label float-left" for="Urgent">Urgent? </label>
                          <input type="checkbox" name="Urgent">
                      </div>
                      
                      
                      <input type="text" name="Urgent" value="0" id="hideThis">
              <!-- ____ATTACHMENT____ -->
                      <div class="form-group">
                          <label class="control-label float-left" for="attach">Attach File</label>
                          <input type="file" name="fileToUpload" id="fileToUpload" class="btn btn-new btn-sm">
                      </div>

                      <div class='modal-footer'>
                        <button class="btn btn-new btn-lg" data-toggle="modal" data-dismiss="modal">Cancel</button>
                      </div>
                    </form>
                    </div>
                </div>
              </div>
            </div>



            <!-- ========================= MODAL FOR EDITING THE FORWARD MESSAGE =============================== -->
            @include('inventory::includes._editFile')









          </div>
          <div class="box-footer">
            @if(Session::has('message'))
                <div class="alert alert-success pull-right alertSession" onload="alerts()">{{Session::get('message')}}</div>
                
            @endif


          </div>
        </div>
      </section>
    </div>
@stop

@section('plugins-script')
    <script src="{{asset('adminlte')}}/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="{{asset('adminlte')}}/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="{{asset('adminlte')}}/plugins/daterangepicker/moment.js"></script>
    <script src="{{asset('js')}}/jquery.min.js"></script>
    <script src="{{asset('js')}}/moment.min.js"></script>
    <script src="{{asset('js')}}/fullcalendar.min.js"></script>

@stop

Modules/Inventory/Resources/views/files/files.blade.php
 @extends('template::admin-pages.menus.'.$template['menu']) 

@section('plugins-css')
    <link rel="stylesheet" href="{{asset('adminlte')}}/plugins/datatables/dataTables.bootstrap.css">
@stop

@section('pagename')
    <span style="font-size: 25px;">{{$tite_page}}</span>
@stop

@section('content')
    <div class="content-wrapper">
        <section class="content">
            <div class="box">
                <div class="box-header">
                    <button type="button" class="btn btn-new btn-lg pull-right" data-toggle="modal" data-target="#modal-create-file">Create File &nbsp;&nbsp;&nbsp;
                    <i class="fa fa-user-plus"></i> </button>
                </div>
                <div class="box-body">
                    <div id="searchFile">
                        <form>
                            <input type="text" name="searchFile" placeholder="Search...">
                        </form>
                    </div>
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <td></td>
                                <td>Tracking No.</td>
                                <td>File Name</td>
                                <td>Sender</td>
                                <td>Receiver</td>
                                <td>Department</td>
                                <td>Attachement</td>
                                <td>More</td>
                            </tr>
                            @foreach($per_files as $per_files)
                                <tr>
                                
                                    <td>
                                    @if(($per_files->_important)==0)
                                    <a href="{{ URL::route('EveryFiles.show',$per_files->tracking_no) }}" class="btn btn-function">
                                        <i class="glyphicon glyphicon-flag tooltip" title="Mark as Important" >
                                            <span class="tooltiptext">Mark as Important</span>    
                                        </i>
                                    </a>
                                    @elseif(($per_files->_important)==1)
                                    <a href="{{ URL::route('EveryFiles.show',$per_files->tracking_no) }}" class="btn btn-function">
                                        <i class="glyphicon glyphicon-heart tooltip" title="Mark as Not Important">
                                            <span class="tooltiptext">Mark as Not Important</span>
                                        </i>
                                    </a>
                                    @endif
                                    </td>
                                    <td>{{$per_files->tracking_no}}</td>
                                    <td>{{$per_files->file_name}}</td>
                                        <td>
                                            @if(($per_files->senderID) == (Auth::user()->emp_id))
                                                ME (=^_^=)!!!
                                            @else
                                                {{$per_files->_extra2}}
                                            @endif
                                        </td>
                                        <td>
                                             @if(($per_files->receiverID) == (Auth::user()->emp_id))
                                                ME (=^_^=)!!!
                                            @else
                                                {{$per_files->_extra1}}
                                            @endif
                                        </td>

                                    <td>{{$per_files->deptID_of_receiver}}</td>
                                    <td>{{$per_files->attachmentID}}</td>
                                    <td class="hidden-xs" >
                                        <a href="{{ URL::route('SpecificFile.show',$per_files->tracking_no) }}" class="btn btn-function" ><i class="glyphicon glyphicon-info-sign"></i></a>
                                        

                                    </td>
                                </tr>
                                
                            @endforeach
                        </thead>
                        <tbody>

                        </tbody>

                    </table>
                    @if(Session::has('message'))
                        <div class="alert alert-success pull-right alertSession" onload="alerts()">{{Session::get('message')}}</div>
                    @endif

                    <!-- _______CREATE FILE_______ -->
                    @include('inventory::files._createFile')

                    <!-- ____________EDIT FILE____________ -->
                    @include('inventory::files._editFile')


                      

                </div>
            </div>
        </section>
    </div>
@stop

@section('plugins-script')
    <script src="{{asset('adminlte')}}/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="{{asset('adminlte')}}/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="{{asset('adminlte')}}/plugins/daterangepicker/moment.js"></script>
    <script src="{{asset('js')}}/jquery.min.js"></script>
    <script src="{{asset('js')}}/moment.min.js"></script>
    <script src="{{asset('js')}}/fullcalendar.min.js"></script>

@stop